# develop 에서 config.yaml 과 달라지는 값만.

auth:
  externalUrl: https://develop-auth.plzhans.com
  jwt:
    issuer: http://develop.plzhans.com
    allowedIssuers:
      - http://develop.plzhans.com
      - http://127.0.0.1:3000

apps-api:
  externalUrl: https://develop.plzhans.com
  web:
    sslCertificate: ${SSL_CERTIFICATE:config/develop/ssl/fullchain.pem}
    sslCertificateKey: ${SSL_CERTIFICATE_KEY:config/develop/ssl/privkey.pem}
  proxy:
    trust: 1
    clientIpHeader: cf-connecting-ip
  swagger:
    enabled: true
    ipRestricted: false

admin:
  jwt:
    issuer: https://develop-admin.plzhans.com

apps-admin-api:
  externalUrl: https://develop-admin.plzhans.com
  proxy:
    trust: 1
    clientIpHeader: cf-connecting-ip
  swagger:
    enabled: true
