# production 에서 config.yaml 과 달라지는 값만.

auth:
  externalUrl: https://auth.plzhans.com
  jwt:
    issuer: https://api.plzhans.com
    allowedIssuers:
      - https://api.plzhans.com

apps-api:
  name: hansapp
  externalUrl: https://plzhans.com
  web:
    sslCertificate: ${SSL_CERTIFICATE:config/production/ssl/fullchain.pem}
    sslCertificateKey: ${SSL_CERTIFICATE_KEY:config/production/ssl/privkey.pem}
  proxy:
    trust: 1
    clientIpHeader: cf-connecting-ip
  swagger:
    enabled: true
  sentry:
    enabled: true

admin:
  jwt:
    issuer: https://admin.plzhans.com

apps-admin-api:
  externalUrl: https://admin.plzhans.com
  proxy:
    trust: 1
    clientIpHeader: cf-connecting-ip
  sentry:
    enabled: true

apps-batch:
  sentry:
    enabled: true
