/**
 * 통합 코드 시드 (healthcare_code).
 *
 * 이 파일이 코드 매핑의 **유일한 원본**이다. DB 에 직접 INSERT 하지 않는다.
 * git 에 남고, 어느 환경에나 같은 값이 들어가고, 누가 언제 바꿨는지 추적된다.
 *
 * [1:N 매핑이 필요한 이유]
 * 원본이 같은 과목을 신·구 이름으로 두 코드에 나눠 갖고 있다.
 *   방사선종양학과 = NMC D031 (현행) + D019 (치료방사선과, 옛 이름)
 *   진단검사의학과 = NMC D033 (현행) + D020 (임상병리과, 옛 이름)
 * 병원이 옛 코드를 달고 있어도 우리 코드로는 하나가 되어야 한다.
 *
 * [매핑하지 않는 것]
 *   HIRA 00 일반의        전문의가 없다는 뜻이지 진료과목이 아니다
 *   HIRA 60/90 치과·한방소계  합계 행이다
 *   NMC D057~D060         병무청·의무대·학교시설·기타 — 기관 종류지 과목이 아니다
 * 이런 것은 hospital 적재 때 무시한다. 배치가 "매핑 없음" 으로 경고하지 않도록 여기 명시한다.
 */

export interface HealthcareCodeSeed {
  tp: 'subject' | 'class' | 'equipment' | 'severe' | 'specialty' | 'special';
  cd: string;

  /**
   * 관리용 한국어 이름. **시스템/운영이 코드를 식별하는 라벨이다.**
   * 화면에 그대로 내보내지 않는다 — 표시는 title 을 쓴다. 이름의 최종 폴백이기도 하다.
   */
  nm: string;

  /**
   * 표시용 한국어 이름. **API 가 클라이언트에 내보내는 이름이다.**
   * 생략하면 시드 적재 때 nm 을 복사한다. nm 과 달라질 수 있다(더 친근한 표기 등).
   */
  title?: string;

  /** 표시용 영어·일본어·중국어(간체) 이름. 없으면 API 가 title(한국어)로 폴백한다 — 점진적으로 채우면 된다. */
  title_en?: string;
  title_ja?: string;
  title_zh?: string;
  cmt?: string;
  hira_cd?: string[];
  nmc_cd?: string[];
  sort: number;
}

/** 매핑 대상이 아닌 원본 코드. 배치가 경고를 내지 않도록 명시적으로 무시한다. */
export const IGNORED_SOURCE_CODES = {
  subject: {
    hira: ['00', '60', '90'], // 일반의 · 치과소계 · 한방소계
    nmc: ['D057', 'D058', 'D059', 'D060'], // 병무청 · 의무대 · 학교시설 · 기타
  },
  class: {
    // 약국은 우리 도메인이 아니다. 병원과 검색 축이 다르고(영업시간·공휴일 당번),
    // 자식 테이블(진료과목·병상·인력·장비)이 전부 무의미하다. 훗날 다루더라도 별도 도메인이다.
    hira: ['81'],
    //     약국
    //
    // NMC 기관구분에는 병원이 아닌 것이 섞여 있다. 응급의료 정보 시스템이라
    // 이송·신고 기관까지 담기 때문이다. 우리 병원 테이블의 대상이 아니다.
    //
    // 'I'(기타)는 한약국·요양원·정신보건센터가 뒤섞인 잡탕이다. 전수도 아니어서
    // (실측 2026-08: 한약국 22곳 중 18곳이 전남 한 지역) 있으나 없으나 한 데이터다.
    // HIRA 에 있는 조산원은 HIRA 종별로 이미 들어오므로 이 제외에 걸리지 않는다 —
    // 무시는 NMC 단독 병원에만 적용된다.
    nmc: ['H', 'I', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z'],
    //    약국 기타 이송단체 소방서 경찰서 지자체 구급차 중앙응급의료센터 정보센터
  },
} as const;

// ── 진료과목 ────────────────────────────────────────────────
// HIRA 50종 · NMC 57종 → 통합 47종. 이름으로 44종이 자동 매칭됐고 나머지는 손으로 붙였다.

const SUBJECTS: HealthcareCodeSeed[] = [
  // 의과
  {
    tp: 'subject',
    cd: 'IM',
    nm: '내과',
    title_en: 'Internal Medicine',
    title_ja: '内科',
    title_zh: '内科',
    hira_cd: ['01'],
    nmc_cd: ['D001'],
    sort: 101,
  },
  {
    tp: 'subject',
    cd: 'PED',
    nm: '소아청소년과',
    title_en: 'Pediatrics',
    title_ja: '小児科',
    title_zh: '儿科',
    hira_cd: ['11'],
    nmc_cd: ['D002'],
    sort: 102,
  },
  {
    tp: 'subject',
    cd: 'NEURO',
    nm: '신경과',
    title_en: 'Neurology',
    title_ja: '神経内科',
    title_zh: '神经内科',
    hira_cd: ['02'],
    nmc_cd: ['D003'],
    sort: 103,
  },
  {
    tp: 'subject',
    cd: 'PSY',
    nm: '정신건강의학과',
    title_en: 'Psychiatry',
    title_ja: '精神科',
    title_zh: '精神科',
    hira_cd: ['03'],
    nmc_cd: ['D004'],
    sort: 104,
  },
  {
    tp: 'subject',
    cd: 'DERM',
    nm: '피부과',
    title_en: 'Dermatology',
    title_ja: '皮膚科',
    title_zh: '皮肤科',
    hira_cd: ['14'],
    nmc_cd: ['D005'],
    sort: 105,
  },
  {
    tp: 'subject',
    cd: 'GS',
    nm: '외과',
    title_en: 'General Surgery',
    title_ja: '外科',
    title_zh: '外科',
    hira_cd: ['04'],
    nmc_cd: ['D006'],
    sort: 106,
  },
  {
    tp: 'subject',
    cd: 'CS',
    nm: '심장혈관흉부외과',
    title_en: 'Cardiothoracic Surgery',
    title_ja: '心臓血管外科',
    title_zh: '心脏血管胸外科',
    hira_cd: ['07'],
    nmc_cd: ['D007'],
    sort: 107,
  },
  {
    tp: 'subject',
    cd: 'OS',
    nm: '정형외과',
    title_en: 'Orthopedic Surgery',
    title_ja: '整形外科',
    title_zh: '骨科',
    hira_cd: ['05'],
    nmc_cd: ['D008'],
    sort: 108,
  },
  {
    tp: 'subject',
    cd: 'NS',
    nm: '신경외과',
    title_en: 'Neurosurgery',
    title_ja: '脳神経外科',
    title_zh: '神经外科',
    hira_cd: ['06'],
    nmc_cd: ['D009'],
    sort: 109,
  },
  {
    tp: 'subject',
    cd: 'PS',
    nm: '성형외과',
    title_en: 'Plastic Surgery',
    title_ja: '形成外科',
    title_zh: '整形外科',
    hira_cd: ['08'],
    nmc_cd: ['D010'],
    sort: 110,
  },
  {
    tp: 'subject',
    cd: 'OBGY',
    nm: '산부인과',
    title_en: 'Obstetrics & Gynecology',
    title_ja: '産婦人科',
    title_zh: '妇产科',
    hira_cd: ['10'],
    nmc_cd: ['D011'],
    sort: 111,
  },
  {
    tp: 'subject',
    cd: 'OPH',
    nm: '안과',
    title_en: 'Ophthalmology',
    title_ja: '眼科',
    title_zh: '眼科',
    hira_cd: ['12'],
    nmc_cd: ['D012'],
    sort: 112,
  },
  {
    tp: 'subject',
    cd: 'ENT',
    nm: '이비인후과',
    title_en: 'Otolaryngology',
    title_ja: '耳鼻咽喉科',
    title_zh: '耳鼻喉科',
    hira_cd: ['13'],
    nmc_cd: ['D013'],
    sort: 113,
  },
  {
    tp: 'subject',
    cd: 'URO',
    nm: '비뇨의학과',
    title_en: 'Urology',
    title_ja: '泌尿器科',
    title_zh: '泌尿外科',
    hira_cd: ['15'],
    nmc_cd: ['D014'],
    sort: 114,
  },
  {
    tp: 'subject',
    cd: 'TB',
    nm: '결핵과',
    title_en: 'Tuberculosis',
    title_ja: '結核科',
    title_zh: '结核科',
    hira_cd: ['20'],
    nmc_cd: ['D015'],
    sort: 115,
  },
  {
    tp: 'subject',
    cd: 'REHAB',
    nm: '재활의학과',
    title_en: 'Rehabilitation Medicine',
    title_ja: 'リハビリテーション科',
    title_zh: '康复医学科',
    hira_cd: ['21'],
    nmc_cd: ['D016'],
    sort: 116,
  },
  {
    tp: 'subject',
    cd: 'ANES',
    nm: '마취통증의학과',
    title_en: 'Anesthesiology & Pain Medicine',
    title_ja: '麻酔科・ペインクリニック',
    title_zh: '麻醉疼痛科',
    hira_cd: ['09'],
    nmc_cd: ['D017'],
    sort: 117,
  },
  {
    tp: 'subject',
    cd: 'RAD',
    nm: '영상의학과',
    title_en: 'Radiology',
    title_ja: '放射線科',
    title_zh: '影像医学科',
    hira_cd: ['16'],
    nmc_cd: ['D018'],
    sort: 118,
  },
  {
    tp: 'subject',
    cd: 'RAD_ONC',
    nm: '방사선종양학과',
    title_en: 'Radiation Oncology',
    title_ja: '放射線腫瘍科',
    title_zh: '放射肿瘤科',
    cmt: 'NMC D019(치료방사선과)는 같은 과목의 옛 이름이다',
    hira_cd: ['17'],
    nmc_cd: ['D031', 'D019'],
    sort: 119,
  },
  {
    tp: 'subject',
    cd: 'PATH',
    nm: '병리과',
    title_en: 'Pathology',
    title_ja: '病理科',
    title_zh: '病理科',
    cmt: 'NMC D021(해부병리과)은 같은 과목의 옛 이름이다',
    hira_cd: ['18'],
    nmc_cd: ['D032', 'D021'],
    sort: 120,
  },
  {
    tp: 'subject',
    cd: 'LAB',
    nm: '진단검사의학과',
    title_en: 'Laboratory Medicine',
    title_ja: '臨床検査科',
    title_zh: '检验医学科',
    cmt: 'NMC D020(임상병리과)은 같은 과목의 옛 이름이다',
    hira_cd: ['19'],
    nmc_cd: ['D033', 'D020'],
    sort: 121,
  },
  {
    tp: 'subject',
    cd: 'NM',
    nm: '핵의학과',
    title_en: 'Nuclear Medicine',
    title_ja: '核医学科',
    title_zh: '核医学科',
    hira_cd: ['22'],
    nmc_cd: ['D023'],
    sort: 122,
  },
  {
    tp: 'subject',
    cd: 'FM',
    nm: '가정의학과',
    title_en: 'Family Medicine',
    title_ja: '家庭医学科',
    title_zh: '家庭医学科',
    hira_cd: ['23'],
    nmc_cd: ['D022'],
    sort: 123,
  },
  {
    tp: 'subject',
    cd: 'EM',
    nm: '응급의학과',
    title_en: 'Emergency Medicine',
    title_ja: '救急医学科',
    title_zh: '急诊医学科',
    hira_cd: ['24'],
    nmc_cd: ['D024'],
    sort: 124,
  },
  {
    tp: 'subject',
    cd: 'OCC_ENV',
    nm: '직업환경의학과',
    title_en: 'Occupational & Environmental Medicine',
    title_ja: '産業環境医学科',
    title_zh: '职业环境医学科',
    cmt: 'NMC D025(산업의학과)는 옛 이름이다',
    hira_cd: ['25'],
    nmc_cd: ['D053', 'D025'],
    sort: 125,
  },
  {
    tp: 'subject',
    cd: 'PREV',
    nm: '예방의학과',
    title_en: 'Preventive Medicine',
    title_ja: '予防医学科',
    title_zh: '预防医学科',
    hira_cd: ['26'],
    nmc_cd: ['D029'],
    sort: 126,
  },

  // 치과
  {
    tp: 'subject',
    cd: 'DENT',
    nm: '치과',
    title_en: 'Dentistry',
    title_ja: '歯科',
    title_zh: '牙科',
    hira_cd: ['49'],
    nmc_cd: ['D026'],
    sort: 201,
  },
  {
    tp: 'subject',
    cd: 'OMFS',
    nm: '구강악안면외과',
    title_en: 'Oral & Maxillofacial Surgery',
    title_ja: '口腔顎顔面外科',
    title_zh: '口腔颌面外科',
    cmt: 'NMC D054(구강안면외과)는 같은 과목의 다른 표기다',
    hira_cd: ['50'],
    nmc_cd: ['D034', 'D054'],
    sort: 202,
  },
  {
    tp: 'subject',
    cd: 'PROS',
    nm: '치과보철과',
    title_en: 'Prosthodontics',
    title_ja: '歯科補綴科',
    title_zh: '口腔修复科',
    hira_cd: ['51'],
    nmc_cd: ['D035'],
    sort: 203,
  },
  {
    tp: 'subject',
    cd: 'ORTHO',
    nm: '치과교정과',
    title_en: 'Orthodontics',
    title_ja: '歯科矯正科',
    title_zh: '口腔正畸科',
    hira_cd: ['52'],
    nmc_cd: ['D036'],
    sort: 204,
  },
  {
    tp: 'subject',
    cd: 'PEDO',
    nm: '소아치과',
    title_en: 'Pediatric Dentistry',
    title_ja: '小児歯科',
    title_zh: '儿童口腔科',
    hira_cd: ['53'],
    nmc_cd: ['D037'],
    sort: 205,
  },
  {
    tp: 'subject',
    cd: 'PERIO',
    nm: '치주과',
    title_en: 'Periodontics',
    title_ja: '歯周科',
    title_zh: '牙周科',
    hira_cd: ['54'],
    nmc_cd: ['D038'],
    sort: 206,
  },
  {
    tp: 'subject',
    cd: 'ENDO',
    nm: '치과보존과',
    title_en: 'Endodontics',
    title_ja: '歯科保存科',
    title_zh: '牙体牙髓科',
    hira_cd: ['55'],
    nmc_cd: ['D039'],
    sort: 207,
  },
  {
    tp: 'subject',
    cd: 'OMED',
    nm: '구강내과',
    title_en: 'Oral Medicine',
    title_ja: '口腔内科',
    title_zh: '口腔内科',
    hira_cd: ['56'],
    nmc_cd: ['D040'],
    sort: 208,
  },
  {
    tp: 'subject',
    cd: 'ORAD',
    nm: '영상치의학과',
    title_en: 'Oral & Maxillofacial Radiology',
    title_ja: '歯科放射線科',
    title_zh: '口腔颌面影像科',
    cmt: 'NMC D041(구강악안면방사선과)은 옛 이름이다',
    hira_cd: ['57'],
    nmc_cd: ['D055', 'D041'],
    sort: 209,
  },
  {
    tp: 'subject',
    cd: 'OPATH',
    nm: '구강병리과',
    title_en: 'Oral Pathology',
    title_ja: '口腔病理科',
    title_zh: '口腔病理科',
    hira_cd: ['58'],
    nmc_cd: ['D042'],
    sort: 210,
  },
  {
    tp: 'subject',
    cd: 'PREV_DENT',
    nm: '예방치과',
    title_en: 'Preventive Dentistry',
    title_ja: '予防歯科',
    title_zh: '预防牙科',
    hira_cd: ['59'],
    nmc_cd: ['D043'],
    sort: 211,
  },
  {
    tp: 'subject',
    cd: 'INTEG_DENT',
    nm: '통합치의학과',
    title_en: 'Integrated Dentistry',
    title_ja: '統合歯科',
    title_zh: '综合口腔科',
    hira_cd: ['61'],
    nmc_cd: ['D056'],
    sort: 212,
  },

  // 한방
  {
    tp: 'subject',
    cd: 'KM_IM',
    nm: '한방내과',
    title_en: 'Korean Internal Medicine',
    title_ja: '韓方内科',
    title_zh: '韩医内科',
    hira_cd: ['80'],
    nmc_cd: ['D044'],
    sort: 301,
  },
  {
    tp: 'subject',
    cd: 'KM_OBGY',
    nm: '한방부인과',
    title_en: 'Korean Obstetrics & Gynecology',
    title_ja: '韓方婦人科',
    title_zh: '韩医妇科',
    hira_cd: ['81'],
    nmc_cd: ['D045'],
    sort: 302,
  },
  {
    tp: 'subject',
    cd: 'KM_PED',
    nm: '한방소아과',
    title_en: 'Korean Pediatrics',
    title_ja: '韓方小児科',
    title_zh: '韩医儿科',
    hira_cd: ['82'],
    nmc_cd: ['D046'],
    sort: 303,
  },
  {
    tp: 'subject',
    cd: 'KM_ENT_DERM',
    nm: '한방안·이비인후·피부과',
    title_en: 'Korean Ophthalmology, Otolaryngology & Dermatology',
    title_ja: '韓方眼・耳鼻咽喉・皮膚科',
    title_zh: '韩医眼耳鼻喉皮肤科',
    hira_cd: ['83'],
    nmc_cd: ['D047'],
    sort: 304,
  },
  {
    tp: 'subject',
    cd: 'KM_PSY',
    nm: '한방신경정신과',
    title_en: 'Korean Neuropsychiatry',
    title_ja: '韓方神経精神科',
    title_zh: '韩医神经精神科',
    hira_cd: ['84'],
    nmc_cd: ['D048'],
    sort: 305,
  },
  {
    tp: 'subject',
    cd: 'KM_REHAB',
    nm: '한방재활의학과',
    title_en: 'Korean Rehabilitation Medicine',
    title_ja: '韓方リハビリテーション科',
    title_zh: '韩医康复医学科',
    hira_cd: ['86'],
    nmc_cd: ['D049'],
    sort: 306,
  },
  {
    tp: 'subject',
    cd: 'KM_SASANG',
    nm: '사상체질과',
    title_en: 'Sasang Constitutional Medicine',
    title_ja: '四象体質科',
    title_zh: '四象体质科',
    hira_cd: ['87'],
    nmc_cd: ['D050'],
    sort: 307,
  },
  {
    tp: 'subject',
    cd: 'KM_ACU',
    nm: '침구과',
    title_en: 'Acupuncture & Moxibustion',
    title_ja: '鍼灸科',
    title_zh: '针灸科',
    hira_cd: ['85'],
    nmc_cd: ['D051'],
    sort: 308,
  },
  {
    tp: 'subject',
    cd: 'KM_EM',
    nm: '한방응급',
    title_en: 'Korean Emergency Medicine',
    title_ja: '韓方救急',
    title_zh: '韩医急诊',
    hira_cd: ['88'],
    nmc_cd: ['D052'],
    sort: 309,
  },
];

// ── 종별 ────────────────────────────────────────────────────
// HIRA clCd 19종 · NMC dutyDiv 25종. 두 체계가 크게 다르다.
//   HIRA 는 요양기관 종별(청구 기준), NMC 는 응급의료 관점의 기관구분이다.
//   NMC 에는 이송단체·소방서·경찰서·지자체까지 들어 있어 병원이 아닌 것이 많다.

const CLASSES: HealthcareCodeSeed[] = [
  {
    tp: 'class',
    cd: 'TERTIARY',
    nm: '상급종합병원',
    title_en: 'Tertiary General Hospital',
    title_ja: '上級総合病院',
    title_zh: '上级综合医院',
    hira_cd: ['01'],
    sort: 1,
  },
  {
    tp: 'class',
    cd: 'GENERAL',
    nm: '종합병원',
    title_en: 'General Hospital',
    title_ja: '総合病院',
    title_zh: '综合医院',
    hira_cd: ['11'],
    nmc_cd: ['A'],
    sort: 2,
  },
  {
    tp: 'class',
    cd: 'HOSPITAL',
    nm: '병원',
    title_en: 'Hospital',
    title_ja: '病院',
    title_zh: '医院',
    hira_cd: ['21'],
    nmc_cd: ['B'],
    sort: 3,
  },
  {
    tp: 'class',
    cd: 'SPECIALTY',
    nm: '전문병원',
    title_en: 'Specialty Hospital',
    title_ja: '専門病院',
    title_zh: '专科医院',
    cmt: 'HIRA 만 별도 종별로 둔다',
    hira_cd: ['05'],
    sort: 4,
  },
  {
    tp: 'class',
    cd: 'CLINIC',
    nm: '의원',
    title_en: 'Clinic',
    title_ja: '医院',
    title_zh: '诊所',
    hira_cd: ['31'],
    nmc_cd: ['C'],
    sort: 5,
  },
  {
    tp: 'class',
    cd: 'NURSING',
    nm: '요양병원',
    title_en: 'Nursing Hospital',
    title_ja: '療養病院',
    title_zh: '疗养医院',
    hira_cd: ['28'],
    nmc_cd: ['D'],
    sort: 6,
  },
  {
    tp: 'class',
    cd: 'MENTAL',
    nm: '정신병원',
    title_en: 'Psychiatric Hospital',
    title_ja: '精神病院',
    title_zh: '精神病院',
    cmt: 'HIRA 는 clCd 29 로 주는데 코드 목록에는 없다. 병원 데이터에는 존재한다.',
    hira_cd: ['29'],
    nmc_cd: ['L'],
    sort: 7,
  },
  {
    tp: 'class',
    cd: 'DENTAL_HOSP',
    nm: '치과병원',
    title_en: 'Dental Hospital',
    title_ja: '歯科病院',
    title_zh: '牙科医院',
    hira_cd: ['41'],
    nmc_cd: ['M'],
    sort: 8,
  },
  {
    tp: 'class',
    cd: 'DENTAL_CLINIC',
    nm: '치과의원',
    title_en: 'Dental Clinic',
    title_ja: '歯科医院',
    title_zh: '牙科诊所',
    hira_cd: ['51'],
    nmc_cd: ['N'],
    sort: 9,
  },
  {
    tp: 'class',
    cd: 'KM_GENERAL',
    nm: '한방종합병원',
    title_en: 'Korean Medicine General Hospital',
    title_ja: '韓方総合病院',
    title_zh: '韩医综合医院',
    hira_cd: ['91'],
    sort: 10,
  },
  {
    tp: 'class',
    cd: 'KM_HOSPITAL',
    nm: '한방병원',
    title_en: 'Korean Medicine Hospital',
    title_ja: '韓方病院',
    title_zh: '韩医医院',
    hira_cd: ['92'],
    nmc_cd: ['E'],
    sort: 11,
  },
  {
    tp: 'class',
    cd: 'KM_CLINIC',
    nm: '한의원',
    title_en: 'Korean Medicine Clinic',
    title_ja: '韓医院',
    title_zh: '韩医诊所',
    hira_cd: ['93'],
    nmc_cd: ['G'],
    sort: 12,
  },
  {
    tp: 'class',
    cd: 'MIDWIFE',
    nm: '조산원',
    title_en: 'Midwifery Clinic',
    title_ja: '助産院',
    title_zh: '助产院',
    hira_cd: ['61'],
    nmc_cd: ['P'],
    sort: 13,
  },
  {
    tp: 'class',
    cd: 'HEALTH_CENTER',
    nm: '보건소',
    title_en: 'Public Health Center',
    title_ja: '保健所',
    title_zh: '保健所',
    hira_cd: ['71'],
    nmc_cd: ['R'],
    sort: 14,
  },
  {
    tp: 'class',
    cd: 'HEALTH_SUB',
    nm: '보건지소',
    title_en: 'Public Health Subcenter',
    title_ja: '保健支所',
    title_zh: '保健支所',
    hira_cd: ['72'],
    sort: 15,
  },
  {
    tp: 'class',
    cd: 'HEALTH_POST',
    nm: '보건진료소',
    title_en: 'Primary Health Care Post',
    title_ja: '保健診療所',
    title_zh: '保健诊疗所',
    hira_cd: ['73'],
    sort: 16,
  },
  {
    tp: 'class',
    cd: 'HEALTH_MED',
    nm: '보건의료원',
    title_en: 'Public Health Medical Center',
    title_ja: '保健医療院',
    title_zh: '保健医疗院',
    hira_cd: ['75'],
    sort: 17,
  },
  // 약국(PHARMACY)은 여기 없다. 병원 종별이 아니라 별도 도메인이고, 원본 코드
  // (HIRA 81 · NMC H)는 IGNORED_SOURCE_CODES 에서 명시적으로 무시한다.
  {
    tp: 'class',
    cd: 'TB_HOSP',
    nm: '결핵병원',
    title_en: 'Tuberculosis Hospital',
    title_ja: '結核病院',
    title_zh: '结核病院',
    cmt: 'NMC 만 구분한다',
    nmc_cd: ['J'],
    sort: 19,
  },
  {
    tp: 'class',
    cd: 'LEPROSY_HOSP',
    nm: '한센병원',
    title_en: 'Leprosy Hospital',
    title_ja: 'ハンセン病院',
    title_zh: '麻风病院',
    nmc_cd: ['K'],
    sort: 20,
  },
  {
    tp: 'class',
    cd: 'GERIATRIC',
    nm: '노인전문병원',
    title_en: 'Geriatric Hospital',
    title_ja: '老人専門病院',
    title_zh: '老年专科医院',
    nmc_cd: ['F'],
    sort: 21,
  },
  {
    tp: 'class',
    cd: 'DEMENTIA',
    nm: '치매병원',
    title_en: 'Dementia Hospital',
    title_ja: '認知症病院',
    title_zh: '认知症医院',
    nmc_cd: ['Q'],
    sort: 22,
  },
  {
    tp: 'class',
    cd: 'ETC',
    nm: '기타',
    title_en: 'Other',
    title_ja: 'その他',
    title_zh: '其他',
    hira_cd: ['99', 'AA'],
    nmc_cd: ['I', 'O'],
    sort: 99,
  },
];

// ── 장비 ────────────────────────────────────────────────────
// HIRA 만 코드를 준다. NMC 는 basic 의 개별 필드(hvgc 등)로 일부만 알 수 있다.

const EQUIPMENTS: HealthcareCodeSeed[] = [
  {
    tp: 'equipment',
    cd: 'XRAY',
    nm: '일반엑스선촬영장치',
    title_en: 'X-ray',
    title_ja: '一般X線撮影装置',
    title_zh: '普通X线摄影装置',
    hira_cd: ['B101'],
    sort: 1,
  },
  {
    tp: 'equipment',
    cd: 'MAMMO',
    nm: '유방촬영장치',
    title_en: 'Mammography',
    title_ja: 'マンモグラフィ',
    title_zh: '乳腺摄影装置',
    hira_cd: ['B105'],
    sort: 2,
  },
  {
    tp: 'equipment',
    cd: 'CT',
    nm: 'CT',
    title_en: 'CT',
    title_ja: 'CT',
    title_zh: 'CT',
    hira_cd: ['B108'],
    sort: 3,
  },
  {
    tp: 'equipment',
    cd: 'CBCT',
    nm: '콘빔CT',
    title_en: 'Cone Beam CT',
    title_ja: 'コーンビームCT',
    title_zh: '锥形束CT',
    hira_cd: ['B109'],
    sort: 4,
  },
  {
    tp: 'equipment',
    cd: 'MRI',
    nm: 'MRI',
    title_en: 'MRI',
    title_ja: 'MRI',
    title_zh: 'MRI',
    hira_cd: ['B301'],
    sort: 5,
  },
  {
    tp: 'equipment',
    cd: 'PET',
    nm: '양전자단층촬영기(PET)',
    title_en: 'PET',
    title_ja: 'PET',
    title_zh: '正电子发射断层扫描(PET)',
    hira_cd: ['B201'],
    sort: 6,
  },
  {
    tp: 'equipment',
    cd: 'US',
    nm: '초음파영상진단기',
    title_en: 'Ultrasound',
    title_ja: '超音波診断装置',
    title_zh: '超声影像诊断仪',
    hira_cd: ['B302'],
    sort: 7,
  },
  {
    tp: 'equipment',
    cd: 'BMD',
    nm: '골밀도검사기',
    title_en: 'Bone Densitometer',
    title_ja: '骨密度測定装置',
    title_zh: '骨密度检查仪',
    hira_cd: ['B203'],
    sort: 8,
  },
  {
    tp: 'equipment',
    cd: 'GAMMA_KNIFE',
    nm: '종양치료기(감마나이프)',
    title_en: 'Gamma Knife',
    title_ja: 'ガンマナイフ',
    title_zh: '肿瘤治疗仪(伽玛刀)',
    hira_cd: ['B403'],
    sort: 9,
  },
  {
    tp: 'equipment',
    cd: 'CYBER_KNIFE',
    nm: '종양치료기(사이버나이프)',
    title_en: 'CyberKnife',
    title_ja: 'サイバーナイフ',
    title_zh: '肿瘤治疗仪(射波刀)',
    hira_cd: ['B404'],
    sort: 10,
  },
  {
    tp: 'equipment',
    cd: 'PROTON',
    nm: '종양치료기(양성자치료기)',
    title_en: 'Proton Therapy',
    title_ja: '陽子線治療装置',
    title_zh: '肿瘤治疗仪(质子治疗)',
    hira_cd: ['B407'],
    sort: 11,
  },
  {
    tp: 'equipment',
    cd: 'VENTILATOR',
    nm: '인공호흡기',
    title_en: 'Ventilator',
    title_ja: '人工呼吸器',
    title_zh: '呼吸机',
    hira_cd: ['D202'],
    sort: 12,
  },
  {
    tp: 'equipment',
    cd: 'ECMO',
    nm: 'ECMO',
    title_en: 'ECMO',
    title_ja: 'ECMO',
    title_zh: 'ECMO',
    hira_cd: ['D206'],
    sort: 13,
  },
  {
    tp: 'equipment',
    cd: 'INCUBATOR',
    nm: '인큐베이터',
    title_en: 'Incubator',
    title_ja: '保育器',
    title_zh: '保温箱',
    hira_cd: ['D201'],
    sort: 14,
  },
  {
    tp: 'equipment',
    cd: 'DIALYSIS',
    nm: '인공신장기(혈액투석)',
    title_en: 'Hemodialysis Machine',
    title_ja: '人工透析装置',
    title_zh: '人工肾(血液透析)',
    hira_cd: ['D214'],
    sort: 15,
  },
  {
    tp: 'equipment',
    cd: 'ESWL',
    nm: '체외충격파쇄석기',
    title_en: 'Lithotripter (ESWL)',
    title_ja: '体外衝撃波結石破砕装置',
    title_zh: '体外冲击波碎石机',
    hira_cd: ['D212'],
    sort: 16,
  },
  {
    tp: 'equipment',
    cd: 'FETAL_MONITOR',
    nm: '분만감시기',
    title_en: 'Fetal Monitor',
    title_ja: '分娩監視装置',
    title_zh: '胎儿监护仪',
    hira_cd: ['A240'],
    sort: 17,
  },
];

// ── 중증질환 처치가능 ───────────────────────────────────────
// NMC 만 준다 (basic 의 MKioskTy*). 응급 상황에서 "이 병원이 뇌출혈 수술을 할 수 있나" 를 답한다.
// HIRA 에는 대응하는 코드가 없다.

const SEVERE: HealthcareCodeSeed[] = [
  {
    tp: 'severe',
    cd: 'BRAIN_HEMO',
    nm: '뇌출혈수술',
    title_en: 'Intracranial Hemorrhage Surgery',
    title_ja: '脳出血手術',
    title_zh: '脑出血手术',
    nmc_cd: ['MKioskTy1'],
    sort: 1,
  },
  {
    tp: 'severe',
    cd: 'BRAIN_ISCH',
    nm: '뇌경색의재관류',
    title_en: 'Ischemic Stroke Reperfusion',
    title_ja: '脳梗塞の再灌流',
    title_zh: '脑梗死再灌注',
    nmc_cd: ['MKioskTy2'],
    sort: 2,
  },
  {
    tp: 'severe',
    cd: 'MI',
    nm: '심근경색의재관류',
    title_en: 'Myocardial Infarction Reperfusion',
    title_ja: '心筋梗塞の再灌流',
    title_zh: '心肌梗死再灌注',
    nmc_cd: ['MKioskTy3'],
    sort: 3,
  },
  {
    tp: 'severe',
    cd: 'ABDOMEN',
    nm: '복부손상의수술',
    title_en: 'Abdominal Trauma Surgery',
    title_ja: '腹部損傷の手術',
    title_zh: '腹部损伤手术',
    nmc_cd: ['MKioskTy4'],
    sort: 4,
  },
  {
    tp: 'severe',
    cd: 'LIMB',
    nm: '사지접합의수술',
    title_en: 'Limb Replantation',
    title_ja: '四肢接合の手術',
    title_zh: '断肢再植手术',
    nmc_cd: ['MKioskTy5'],
    sort: 5,
  },
  {
    tp: 'severe',
    cd: 'ENDOSCOPY',
    nm: '응급내시경',
    title_en: 'Emergency Endoscopy',
    title_ja: '緊急内視鏡',
    title_zh: '急诊内镜',
    nmc_cd: ['MKioskTy6'],
    sort: 6,
  },
  {
    tp: 'severe',
    cd: 'DIALYSIS',
    nm: '응급투석',
    title_en: 'Emergency Dialysis',
    title_ja: '緊急透析',
    title_zh: '急诊透析',
    nmc_cd: ['MKioskTy7'],
    sort: 7,
  },
  {
    tp: 'severe',
    cd: 'PRETERM',
    nm: '조산산모',
    title_en: 'Preterm Labor',
    title_ja: '早産妊婦',
    title_zh: '早产孕妇',
    nmc_cd: ['MKioskTy8'],
    sort: 8,
  },
  {
    tp: 'severe',
    cd: 'PSYCH',
    nm: '정신질환자',
    title_en: 'Psychiatric Emergency',
    title_ja: '精神疾患者',
    title_zh: '精神疾病患者',
    nmc_cd: ['MKioskTy9'],
    sort: 9,
  },
  {
    tp: 'severe',
    cd: 'NEONATE',
    nm: '신생아',
    title_en: 'Neonatal Care',
    title_ja: '新生児',
    title_zh: '新生儿',
    nmc_cd: ['MKioskTy10'],
    sort: 10,
  },
  {
    tp: 'severe',
    cd: 'BURN',
    nm: '중증화상',
    title_en: 'Severe Burns',
    title_ja: '重症熱傷',
    title_zh: '重症烧伤',
    nmc_cd: ['MKioskTy11'],
    sort: 11,
  },
  {
    tp: 'severe',
    cd: 'ER_GATEKEEPER',
    nm: '응급실(Emergency gate keeper)',
    title_en: 'Emergency Gatekeeper',
    title_ja: '救急室(Emergency gate keeper)',
    title_zh: '急诊室(Emergency gate keeper)',
    nmc_cd: ['MKioskTy25'],
    sort: 25,
  },
];

// ── 전문병원 지정분야 ───────────────────────────────────────
// HIRA 만 준다 (getSpcHospCodeList, srchCd 19종). 보건복지부가 분야별로 지정한 전문병원이다.
// severe 와 같은 성격 — "이 병원이 무엇에 특화됐나" 를 코드로 말한다. 그래서 capability 로 묶인다.
//   원본 코드는 2자리 숫자(47=심장)와 D1(주산기) 이 섞여 있다. 우리 코드로 통일한다.
//   지정 병원이 0곳인 분야(한방부인과)도 코드로는 존재하므로 19종을 다 매핑한다 —
//   빠지면 나중에 그 분야 병원이 생겼을 때 배치가 "매핑 없음" 으로 값을 버린다.

const SPECIALTIES: HealthcareCodeSeed[] = [
  {
    tp: 'specialty',
    cd: 'OBGY',
    nm: '산부인과',
    title_en: 'Obstetrics & Gynecology',
    title_ja: '産婦人科',
    title_zh: '妇产科',
    hira_cd: ['34'],
    sort: 1,
  },
  {
    tp: 'specialty',
    cd: 'PED',
    nm: '소아청소년과',
    title_en: 'Pediatrics',
    title_ja: '小児科',
    title_zh: '儿科',
    hira_cd: ['35'],
    sort: 2,
  },
  {
    tp: 'specialty',
    cd: 'NEURO',
    nm: '신경과',
    title_en: 'Neurology',
    title_ja: '神経内科',
    title_zh: '神经内科',
    hira_cd: ['36'],
    sort: 3,
  },
  {
    tp: 'specialty',
    cd: 'OPH',
    nm: '안과',
    title_en: 'Ophthalmology',
    title_ja: '眼科',
    title_zh: '眼科',
    hira_cd: ['38'],
    sort: 4,
  },
  {
    tp: 'specialty',
    cd: 'GS',
    nm: '외과',
    title_en: 'General Surgery',
    title_ja: '外科',
    title_zh: '外科',
    hira_cd: ['39'],
    sort: 5,
  },
  {
    tp: 'specialty',
    cd: 'ENT',
    nm: '이비인후과',
    title_en: 'Otolaryngology',
    title_ja: '耳鼻咽喉科',
    title_zh: '耳鼻喉科',
    hira_cd: ['40'],
    sort: 6,
  },
  {
    tp: 'specialty',
    cd: 'JOINT',
    nm: '관절',
    title_en: 'Joint',
    title_ja: '関節',
    title_zh: '关节',
    hira_cd: ['43'],
    sort: 7,
  },
  {
    tp: 'specialty',
    cd: 'CEREBROVASC',
    nm: '뇌혈관',
    title_en: 'Cerebrovascular',
    title_ja: '脳血管',
    title_zh: '脑血管',
    hira_cd: ['44'],
    sort: 8,
  },
  {
    tp: 'specialty',
    cd: 'COLORECTAL',
    nm: '대장항문',
    title_en: 'Colorectal',
    title_ja: '大腸肛門',
    title_zh: '大肠肛门',
    hira_cd: ['45'],
    sort: 9,
  },
  {
    tp: 'specialty',
    cd: 'REPLANT',
    nm: '수지접합',
    title_en: 'Replantation',
    title_ja: '手指接合',
    title_zh: '断指再植',
    hira_cd: ['46'],
    sort: 10,
  },
  {
    tp: 'specialty',
    cd: 'HEART',
    nm: '심장',
    title_en: 'Cardiac',
    title_ja: '心臓',
    title_zh: '心脏',
    hira_cd: ['47'],
    sort: 11,
  },
  {
    tp: 'specialty',
    cd: 'ALCOHOL',
    nm: '알코올',
    title_en: 'Alcohol',
    title_ja: 'アルコール',
    title_zh: '酒精',
    hira_cd: ['48'],
    sort: 12,
  },
  {
    tp: 'specialty',
    cd: 'BREAST',
    nm: '유방',
    title_en: 'Breast',
    title_ja: '乳房',
    title_zh: '乳腺',
    hira_cd: ['49'],
    sort: 13,
  },
  {
    tp: 'specialty',
    cd: 'SPINE',
    nm: '척추',
    title_en: 'Spine',
    title_ja: '脊椎',
    title_zh: '脊柱',
    hira_cd: ['50'],
    sort: 14,
  },
  {
    tp: 'specialty',
    cd: 'BURN',
    nm: '화상',
    title_en: 'Burn',
    title_ja: '熱傷',
    title_zh: '烧伤',
    hira_cd: ['51'],
    sort: 15,
  },
  {
    tp: 'specialty',
    cd: 'KM_STROKE',
    nm: '한방중풍질환',
    title_en: 'Korean Medicine Stroke',
    title_ja: '韓方中風疾患',
    title_zh: '韩医中风疾病',
    hira_cd: ['52'],
    sort: 16,
  },
  {
    tp: 'specialty',
    cd: 'KM_SPINE',
    nm: '한방척추질환',
    title_en: 'Korean Medicine Spine',
    title_ja: '韓方脊椎疾患',
    title_zh: '韩医脊柱疾病',
    hira_cd: ['53'],
    sort: 17,
  },
  {
    tp: 'specialty',
    cd: 'KM_OBGY',
    nm: '한방부인과',
    title_en: 'Korean Medicine Obstetrics & Gynecology',
    title_ja: '韓方婦人科',
    title_zh: '韩医妇科',
    cmt: '지정 병원이 없어도 코드로는 존재한다',
    hira_cd: ['54'],
    sort: 18,
  },
  {
    tp: 'specialty',
    cd: 'PERINATAL',
    nm: '주산기(모자)',
    title_en: 'Perinatal (Maternal-Fetal)',
    title_ja: '周産期(母子)',
    title_zh: '围产期(母子)',
    hira_cd: ['D1'],
    sort: 19,
  },
];

// ── 특수진료 (진료가능분야) ──────────────────────────────────
// HIRA 만 준다 (getSpclMdlrtCodeList, srchCd 87종). 대부분 시범사업이다 —
// 방문진료·재택의료·치매주치의·중환자실 운영 등 "이 병원이 참여/제공하는 제도" 를 코드로 말한다.
//
// [코드 규칙] specialty 와 달리 우리 코드를 새로 짓지 않고 HIRA 코드를 그대로 canonical 로 쓴다.
//   전문과목(subject)·종별(class)은 HIRA·NMC 두 소스를 하나로 합치느라 우리 코드가 필요했지만,
//   특수진료는 HIRA 단일 소스라 합칠 대상이 없다. 87종에 사람이 읽는 코드를 짓는 비용만 크다.
//   원본이 시범사업이라 자주 바뀌므로(새 사업이 생기면 findUnmapped 가 경고한다) 코드도 원본을 따른다.
//
// [이름] 영어·일본어는 비워 둔다 — 시범사업명이라 공식 번역이 없다. API 가 한국어로 폴백한다.
// [출처] hira_code(tp='special') 스냅샷. 원본 응답의 완전중복 6종은 (tp,cd) 로 이미 합쳐져 있다.

const SPECIAL: HealthcareCodeSeed[] = [
  {
    tp: 'special',
    cd: '02',
    nm: '제3차의료급여기관',
    title_en: 'Tertiary Medical Aid Institution',
    title_ja: '第3次医療給付機関',
    title_zh: '第三次医疗救助机构',
    hira_cd: ['02'],
    sort: 1,
  },
  {
    tp: 'special',
    cd: '03',
    nm: '응급의료기관',
    title_en: 'Emergency Medical Institution',
    title_ja: '救急医療機関',
    title_zh: '急救医疗机构',
    hira_cd: ['03'],
    sort: 2,
  },
  {
    tp: 'special',
    cd: '04',
    nm: '성인 중환자실',
    title_en: 'Adult Intensive Care Unit (ICU)',
    title_ja: '成人集中治療室',
    title_zh: '成人重症监护室',
    hira_cd: ['04'],
    sort: 3,
  },
  {
    tp: 'special',
    cd: '05',
    nm: '신생아 중환자실',
    title_en: 'Neonatal Intensive Care Unit (NICU)',
    title_ja: '新生児集中治療室',
    title_zh: '新生儿重症监护室',
    hira_cd: ['05'],
    sort: 4,
  },
  {
    tp: 'special',
    cd: '06',
    nm: '개방병원',
    title_en: 'Open Hospital',
    title_ja: 'オープン病院',
    title_zh: '开放医院',
    hira_cd: ['06'],
    sort: 5,
  },
  {
    tp: 'special',
    cd: '08',
    nm: '가정간호실시기관',
    title_en: 'Home Nursing Care Institution',
    title_ja: '訪問看護実施機関',
    title_zh: '家庭护理实施机构',
    hira_cd: ['08'],
    sort: 6,
  },
  {
    tp: 'special',
    cd: '09',
    nm: '보훈위탁진료요양기관',
    title_en: 'Veterans Affairs Contracted Care Institution',
    title_ja: '報勲委託診療療養機関',
    title_zh: '报勋委托诊疗疗养机构',
    hira_cd: ['09'],
    sort: 7,
  },
  {
    tp: 'special',
    cd: '10',
    nm: '외국인 근로자 등 의료지원 사업시행 의료기관',
    title_en: 'Migrant Worker Healthcare Support Institution',
    title_ja: '外国人労働者等医療支援事業実施医療機関',
    title_zh: '外籍劳工等医疗支援项目实施医疗机构',
    hira_cd: ['10'],
    sort: 8,
  },
  {
    tp: 'special',
    cd: '16',
    nm: '인공와우 실시기관',
    title_en: 'Cochlear Implant Institution',
    title_ja: '人工内耳実施機関',
    title_zh: '人工耳蜗实施机构',
    hira_cd: ['16'],
    sort: 9,
  },
  {
    tp: 'special',
    cd: '17',
    nm: '측두하악관절자극요법 실시기관',
    title_en: 'Temporomandibular Joint Stimulation Therapy Institution',
    title_ja: '顎関節刺激療法実施機関',
    title_zh: '颞下颌关节刺激疗法实施机构',
    hira_cd: ['17'],
    sort: 10,
  },
  {
    tp: 'special',
    cd: '19',
    nm: '소아 중환자실',
    title_en: 'Pediatric Intensive Care Unit (PICU)',
    title_ja: '小児集中治療室',
    title_zh: '儿童重症监护室',
    hira_cd: ['19'],
    sort: 11,
  },
  {
    tp: 'special',
    cd: '34',
    nm: '산부인과',
    title_en: 'Obstetrics & Gynecology',
    title_ja: '産婦人科',
    title_zh: '妇产科',
    hira_cd: ['34'],
    sort: 12,
  },
  {
    tp: 'special',
    cd: '35',
    nm: '소아청소년과',
    title_en: 'Pediatrics',
    title_ja: '小児科',
    title_zh: '儿科',
    hira_cd: ['35'],
    sort: 13,
  },
  {
    tp: 'special',
    cd: '36',
    nm: '신경과',
    title_en: 'Neurology',
    title_ja: '神経内科',
    title_zh: '神经内科',
    hira_cd: ['36'],
    sort: 14,
  },
  {
    tp: 'special',
    cd: '38',
    nm: '안과',
    title_en: 'Ophthalmology',
    title_ja: '眼科',
    title_zh: '眼科',
    hira_cd: ['38'],
    sort: 15,
  },
  {
    tp: 'special',
    cd: '39',
    nm: '외과',
    title_en: 'General Surgery',
    title_ja: '外科',
    title_zh: '外科',
    hira_cd: ['39'],
    sort: 16,
  },
  {
    tp: 'special',
    cd: '40',
    nm: '이비인후과',
    title_en: 'Otolaryngology',
    title_ja: '耳鼻咽喉科',
    title_zh: '耳鼻喉科',
    hira_cd: ['40'],
    sort: 17,
  },
  {
    tp: 'special',
    cd: '43',
    nm: '관절',
    title_en: 'Joint',
    title_ja: '関節',
    title_zh: '关节',
    hira_cd: ['43'],
    sort: 18,
  },
  {
    tp: 'special',
    cd: '44',
    nm: '뇌혈관',
    title_en: 'Cerebrovascular',
    title_ja: '脳血管',
    title_zh: '脑血管',
    hira_cd: ['44'],
    sort: 19,
  },
  {
    tp: 'special',
    cd: '45',
    nm: '대장항문',
    title_en: 'Colorectal',
    title_ja: '大腸肛門',
    title_zh: '大肠肛门',
    hira_cd: ['45'],
    sort: 20,
  },
  {
    tp: 'special',
    cd: '46',
    nm: '수지접합',
    title_en: 'Digit Replantation',
    title_ja: '手指再接合',
    title_zh: '断指再植',
    hira_cd: ['46'],
    sort: 21,
  },
  {
    tp: 'special',
    cd: '47',
    nm: '심장',
    title_en: 'Cardiac',
    title_ja: '心臓',
    title_zh: '心脏',
    hira_cd: ['47'],
    sort: 22,
  },
  {
    tp: 'special',
    cd: '48',
    nm: '알코올',
    title_en: 'Alcohol',
    title_ja: 'アルコール',
    title_zh: '酒精',
    hira_cd: ['48'],
    sort: 23,
  },
  {
    tp: 'special',
    cd: '49',
    nm: '유방',
    title_en: 'Breast',
    title_ja: '乳房',
    title_zh: '乳腺',
    hira_cd: ['49'],
    sort: 24,
  },
  {
    tp: 'special',
    cd: '50',
    nm: '척추',
    title_en: 'Spine',
    title_ja: '脊椎',
    title_zh: '脊柱',
    hira_cd: ['50'],
    sort: 25,
  },
  {
    tp: 'special',
    cd: '51',
    nm: '화상',
    title_en: 'Burn',
    title_ja: '熱傷',
    title_zh: '烧伤',
    hira_cd: ['51'],
    sort: 26,
  },
  {
    tp: 'special',
    cd: '52',
    nm: '한방중풍질환',
    title_en: 'Korean Medicine Stroke',
    title_ja: '韓方中風疾患',
    title_zh: '韩医中风疾病',
    hira_cd: ['52'],
    sort: 27,
  },
  {
    tp: 'special',
    cd: '53',
    nm: '한방척추질환',
    title_en: 'Korean Medicine Spine',
    title_ja: '韓方脊椎疾患',
    title_zh: '韩医脊柱疾病',
    hira_cd: ['53'],
    sort: 28,
  },
  {
    tp: 'special',
    cd: '54',
    nm: '한방부인과',
    title_en: 'Korean Medicine Obstetrics & Gynecology',
    title_ja: '韓方婦人科',
    title_zh: '韩医妇科',
    hira_cd: ['54'],
    sort: 29,
  },
  {
    tp: 'special',
    cd: '55',
    nm: '입원형 호스피스전문기관',
    title_en: 'Inpatient Hospice Institution',
    title_ja: '入院型ホスピス専門機関',
    title_zh: '住院型安宁疗护专门机构',
    hira_cd: ['55'],
    sort: 30,
  },
  {
    tp: 'special',
    cd: 'AO',
    nm: '비대면진료 시범사업 휴일·야간 진료기관(의료기관)',
    title_en: 'Telemedicine Pilot: Holiday/Night Care (Clinic)',
    title_ja: '非対面診療モデル事業 休日・夜間診療機関(医療機関)',
    title_zh: '远程诊疗试点 休息日·夜间诊疗机构(医疗机构)',
    hira_cd: ['AO'],
    sort: 31,
  },
  {
    tp: 'special',
    cd: 'AP',
    nm: '비대면진료 시범사업 휴일·야간 진료기관(약국)',
    title_en: 'Telemedicine Pilot: Holiday/Night Care (Pharmacy)',
    title_ja: '非対面診療モデル事業 休日・夜間診療機関(薬局)',
    title_zh: '远程诊疗试点 休息日·夜间诊疗机构(药局)',
    hira_cd: ['AP'],
    sort: 32,
  },
  {
    tp: 'special',
    cd: 'AS',
    nm: '비대면진료 시범사업 진료기관(의료기관)',
    title_en: 'Telemedicine Pilot Institution (Clinic)',
    title_ja: '非対面診療モデル事業 診療機関(医療機関)',
    title_zh: '远程诊疗试点诊疗机构(医疗机构)',
    hira_cd: ['AS'],
    sort: 33,
  },
  {
    tp: 'special',
    cd: 'AT',
    nm: '비대면진료 시범사업 진료기관(약국)',
    title_en: 'Telemedicine Pilot Institution (Pharmacy)',
    title_ja: '非対面診療モデル事業 診療機関(薬局)',
    title_zh: '远程诊疗试点诊疗机构(药局)',
    hira_cd: ['AT'],
    sort: 34,
  },
  {
    tp: 'special',
    cd: 'AX',
    nm: '치매관리주치의 시범기관',
    title_en: 'Dementia Care Primary Physician Pilot',
    title_ja: '認知症管理主治医モデル機関',
    title_zh: '认知症管理主治医试点机构',
    hira_cd: ['AX'],
    sort: 35,
  },
  {
    tp: 'special',
    cd: 'AY',
    nm: '치매관리주치의 시범기관(방문진료 실시기관)',
    title_en: 'Dementia Care Primary Physician Pilot (Home Visit)',
    title_ja: '認知症管理主治医モデル機関(訪問診療実施)',
    title_zh: '认知症管理主治医试点机构(上门诊疗)',
    hira_cd: ['AY'],
    sort: 36,
  },
  {
    tp: 'special',
    cd: 'B2',
    nm: '제2기 어린이 재활의료기관 시범사업 지정 기관',
    title_en: 'Phase 2 Pediatric Rehabilitation Institution Pilot',
    title_ja: '第2期こどもリハビリ医療機関モデル事業指定機関',
    title_zh: '第二期儿童康复医疗机构试点指定机构',
    hira_cd: ['B2'],
    sort: 37,
  },
  {
    tp: 'special',
    cd: 'BK',
    nm: '의·한협진 활성화를 위한 5단계 시범기관',
    title_en: 'Medical-Korean Medicine Collaborative Care Pilot (Phase 5)',
    title_ja: '医科・韓方協診活性化 第5段階モデル機関',
    title_zh: '医·韩协诊活化第5阶段试点机构',
    hira_cd: ['BK'],
    sort: 38,
  },
  {
    tp: 'special',
    cd: 'C7',
    nm: '일차의료 한의 방문진료 수가 시범기관',
    title_en: 'Primary Care Korean Medicine Home Visit Pilot',
    title_ja: '一次医療 韓医訪問診療モデル機関',
    title_zh: '初级医疗韩医上门诊疗试点机构',
    hira_cd: ['C7'],
    sort: 39,
  },
  {
    tp: 'special',
    cd: 'C8',
    nm: '결핵환자 재택의료 시범기관',
    title_en: 'Tuberculosis Home Healthcare Pilot',
    title_ja: '結核患者 在宅医療モデル機関',
    title_zh: '结核患者居家医疗试点机构',
    hira_cd: ['C8'],
    sort: 40,
  },
  {
    tp: 'special',
    cd: 'C9',
    nm: '암환자 재택의료 시범기관',
    title_en: 'Cancer Patient Home Healthcare Pilot',
    title_ja: 'がん患者 在宅医療モデル機関',
    title_zh: '癌症患者居家医疗试点机构',
    hira_cd: ['C9'],
    sort: 41,
  },
  {
    tp: 'special',
    cd: 'D1',
    nm: '주산기(모자)',
    title_en: 'Perinatal (Maternal-Fetal)',
    title_ja: '周産期(母子)',
    title_zh: '围产期(母子)',
    hira_cd: ['D1'],
    sort: 42,
  },
  {
    tp: 'special',
    cd: 'F2',
    nm: '경피적 대동맥판삽입 실시기관',
    title_en: 'Transcatheter Aortic Valve Implantation (TAVI)',
    title_ja: '経皮的大動脈弁植込み(TAVI)実施機関',
    title_zh: '经导管主动脉瓣植入(TAVI)实施机构',
    hira_cd: ['F2'],
    sort: 43,
  },
  {
    tp: 'special',
    cd: 'F4',
    nm: '아동 일차의료 심층상담 시범기관',
    title_en: 'Pediatric Primary Care In-depth Consultation Pilot',
    title_ja: 'こども一次医療 詳細相談モデル機関',
    title_zh: '儿童初级医疗深度咨询试点机构',
    hira_cd: ['F4'],
    sort: 44,
  },
  {
    tp: 'special',
    cd: 'F5',
    nm: '조혈모세포이식 실시기관',
    title_en: 'Hematopoietic Stem Cell Transplantation',
    title_ja: '造血幹細胞移植実施機関',
    title_zh: '造血干细胞移植实施机构',
    hira_cd: ['F5'],
    sort: 45,
  },
  {
    tp: 'special',
    cd: 'F9',
    nm: '암환자(요루) 재택의료 시범기관',
    title_en: 'Cancer Patient (Urostomy) Home Healthcare Pilot',
    title_ja: 'がん患者(尿路ストーマ)在宅医療モデル機関',
    title_zh: '癌症患者(尿路造口)居家医疗试点机构',
    hira_cd: ['F9'],
    sort: 46,
  },
  {
    tp: 'special',
    cd: 'G1',
    nm: '그린처방의원',
    title_en: 'Green Prescription Clinic',
    title_ja: 'グリーン処方医院',
    title_zh: '绿色处方诊所',
    hira_cd: ['G1'],
    sort: 47,
  },
  {
    tp: 'special',
    cd: 'GA',
    nm: '중증소아 단기입원서비스 시범기관',
    title_en: 'Severe Pediatric Short-term Admission Service Pilot',
    title_ja: '重症小児 短期入院サービスモデル機関',
    title_zh: '重症儿童短期住院服务试点机构',
    hira_cd: ['GA'],
    sort: 48,
  },
  {
    tp: 'special',
    cd: 'KH',
    nm: '간호간병통합서비스 제공기관',
    title_en: 'Comprehensive Nursing Care Service Institution',
    title_ja: '看護・看病統合サービス提供機関',
    title_zh: '护理·陪护一体化服务提供机构',
    hira_cd: ['KH'],
    sort: 49,
  },
  {
    tp: 'special',
    cd: 'N1',
    nm: '난임시술(체외)',
    title_en: 'Infertility Treatment (IVF)',
    title_ja: '不妊治療(体外受精)',
    title_zh: '不孕治疗(体外受精)',
    hira_cd: ['N1'],
    sort: 50,
  },
  {
    tp: 'special',
    cd: 'N2',
    nm: '난임시술(인공)',
    title_en: 'Infertility Treatment (Artificial Insemination)',
    title_ja: '不妊治療(人工授精)',
    title_zh: '不孕治疗(人工授精)',
    hira_cd: ['N2'],
    sort: 51,
  },
  {
    tp: 'special',
    cd: 'PN',
    nm: '첩약 건강보험 적용 2단계 시범사업',
    title_en: 'Herbal Decoction Insurance Coverage Pilot (Phase 2)',
    title_ja: '煎じ薬 健康保険適用 第2段階モデル事業',
    title_zh: '汤药医保适用第2阶段试点项目',
    hira_cd: ['PN'],
    sort: 52,
  },
  {
    tp: 'special',
    cd: 'S0',
    nm: '장애인 건강 주치의 시범기관(방문진료 실시기관)',
    title_en: 'Disability Health Primary Physician Pilot (Home Visit)',
    title_ja: '障害者健康主治医モデル機関(訪問診療実施)',
    title_zh: '残疾人健康主治医试点机构(上门诊疗)',
    hira_cd: ['S0'],
    sort: 53,
  },
  {
    tp: 'special',
    cd: 'S2',
    nm: '(정신질환)병원기반 시범기관',
    title_en: 'Mental Illness: Hospital-based Pilot',
    title_ja: '(精神疾患)病院基盤モデル機関',
    title_zh: '(精神疾病)医院基础试点机构',
    hira_cd: ['S2'],
    sort: 54,
  },
  {
    tp: 'special',
    cd: 'S3',
    nm: '(정신질환)급성기·낮병동 시범기관',
    title_en: 'Mental Illness: Acute/Day Hospital Pilot',
    title_ja: '(精神疾患)急性期・デイケアモデル機関',
    title_zh: '(精神疾病)急性期·日间病房试点机构',
    hira_cd: ['S3'],
    sort: 55,
  },
  {
    tp: 'special',
    cd: 'S4',
    nm: '(정신질환)병원기반·낮병동 시범기관',
    title_en: 'Mental Illness: Hospital-based/Day Hospital Pilot',
    title_ja: '(精神疾患)病院基盤・デイケアモデル機関',
    title_zh: '(精神疾病)医院基础·日间病房试点机构',
    hira_cd: ['S4'],
    sort: 56,
  },
  {
    tp: 'special',
    cd: 'S5',
    nm: 'HPV 국가예방접종사업 참여기관',
    title_en: 'HPV National Immunization Program Participant',
    title_ja: 'HPV 国家予防接種事業参加機関',
    title_zh: 'HPV国家预防接种项目参与机构',
    hira_cd: ['S5'],
    sort: 57,
  },
  {
    tp: 'special',
    cd: 'S8',
    nm: '소아 야간·휴일진료기관',
    title_en: 'Pediatric Night/Holiday Care Institution',
    title_ja: '小児 夜間・休日診療機関',
    title_zh: '儿童夜间·休息日诊疗机构',
    hira_cd: ['S8'],
    sort: 58,
  },
  {
    tp: 'special',
    cd: 'SB',
    nm: '경피적 좌심방이 폐색술 실시기관',
    title_en: 'Percutaneous Left Atrial Appendage Occlusion',
    title_ja: '経皮的左心耳閉鎖術実施機関',
    title_zh: '经皮左心耳封堵术实施机构',
    hira_cd: ['SB'],
    sort: 59,
  },
  {
    tp: 'special',
    cd: 'SC',
    nm: '자문형 호스피스전문기관',
    title_en: 'Consultative Hospice Institution',
    title_ja: '相談型ホスピス専門機関',
    title_zh: '咨询型安宁疗护专门机构',
    hira_cd: ['SC'],
    sort: 60,
  },
  {
    tp: 'special',
    cd: 'SE',
    nm: '상급종합병원 심층진찰 시범기관',
    title_en: 'Tertiary Hospital In-depth Consultation Pilot',
    title_ja: '上級総合病院 詳細診察モデル機関',
    title_zh: '上级综合医院深度诊察试点机构',
    hira_cd: ['SE'],
    sort: 61,
  },
  {
    tp: 'special',
    cd: 'SG',
    nm: '장애인 건강 주치의 시범기관(전체)',
    title_en: 'Disability Health Primary Physician Pilot (Full)',
    title_ja: '障害者健康主治医モデル機関(全体)',
    title_zh: '残疾人健康主治医试点机构(全部)',
    hira_cd: ['SG'],
    sort: 62,
  },
  {
    tp: 'special',
    cd: 'SH',
    nm: '수면다원검사 실시기관',
    title_en: 'Polysomnography Institution',
    title_ja: '睡眠ポリグラフ検査実施機関',
    title_zh: '多导睡眠监测实施机构',
    hira_cd: ['SH'],
    sort: 63,
  },
  {
    tp: 'special',
    cd: 'SI',
    nm: '차세대염기서열분석 기반 유전자 패널검사 실시기관',
    title_en: 'Next-Generation Sequencing (NGS) Gene Panel Testing',
    title_ja: '次世代シークエンシング(NGS)遺伝子パネル検査実施機関',
    title_zh: '基于二代测序的基因面板检测实施机构',
    hira_cd: ['SI'],
    sort: 64,
  },
  {
    tp: 'special',
    cd: 'SL',
    nm: '심실 보조장치 치료술 실시기관(체외형)',
    title_en: 'Ventricular Assist Device (Extracorporeal)',
    title_ja: '心室補助装置治療(体外型)実施機関',
    title_zh: '心室辅助装置治疗实施机构(体外型)',
    hira_cd: ['SL'],
    sort: 65,
  },
  {
    tp: 'special',
    cd: 'SM',
    nm: '심실 보조장치 치료술 실시기관(이식형)',
    title_en: 'Ventricular Assist Device (Implantable)',
    title_ja: '心室補助装置治療(植込み型)実施機関',
    title_zh: '心室辅助装置治疗实施机构(植入型)',
    hira_cd: ['SM'],
    sort: 66,
  },
  {
    tp: 'special',
    cd: 'SN',
    nm: '심실 보조장치 치료술 실시기관(체외형&이식형)',
    title_en: 'Ventricular Assist Device (Extracorporeal & Implantable)',
    title_ja: '心室補助装置治療(体外型・植込み型)実施機関',
    title_zh: '心室辅助装置治疗实施机构(体外型&植入型)',
    hira_cd: ['SN'],
    sort: 67,
  },
  {
    tp: 'special',
    cd: 'SO',
    nm: '중증소아 재택의료 시범기관',
    title_en: 'Severe Pediatric Home Healthcare Pilot',
    title_ja: '重症小児 在宅医療モデル機関',
    title_zh: '重症儿童居家医疗试点机构',
    hira_cd: ['SO'],
    sort: 68,
  },
  {
    tp: 'special',
    cd: 'SP',
    nm: '일차의료 만성질환관리 실시기관',
    title_en: 'Primary Care Chronic Disease Management',
    title_ja: '一次医療 慢性疾患管理実施機関',
    title_zh: '初级医疗慢性病管理实施机构',
    hira_cd: ['SP'],
    sort: 69,
  },
  {
    tp: 'special',
    cd: 'SQ',
    nm: '선천성 악안면 기형의 치과교정 및 악정형 치료 실시기관',
    title_en: 'Congenital Maxillofacial Anomaly Orthodontic/Orthognathic Treatment',
    title_ja: '先天性顎顔面奇形の歯科矯正・顎矯正治療実施機関',
    title_zh: '先天性颌面畸形口腔正畸及颌骨矫正治疗实施机构',
    hira_cd: ['SQ'],
    sort: 70,
  },
  {
    tp: 'special',
    cd: 'SS',
    nm: '신속대응시스템 시범기관',
    title_en: 'Rapid Response System Pilot',
    title_ja: '迅速対応システムモデル機関',
    title_zh: '快速反应系统试点机构',
    hira_cd: ['SS'],
    sort: 71,
  },
  {
    tp: 'special',
    cd: 'ST',
    nm: '일차의료 방문진료 수가 시범기관',
    title_en: 'Primary Care Home Visit Pilot',
    title_ja: '一次医療 訪問診療モデル機関',
    title_zh: '初级医疗上门诊疗试点机构',
    hira_cd: ['ST'],
    sort: 72,
  },
  {
    tp: 'special',
    cd: 'SU',
    nm: '복막투석 환자 재택관리 시범기관',
    title_en: 'Peritoneal Dialysis Home Management Pilot',
    title_ja: '腹膜透析患者 在宅管理モデル機関',
    title_zh: '腹膜透析患者居家管理试点机构',
    hira_cd: ['SU'],
    sort: 73,
  },
  {
    tp: 'special',
    cd: 'SV',
    nm: '(정신질환)급성기·병원기반 시범기관',
    title_en: 'Mental Illness: Acute/Hospital-based Pilot',
    title_ja: '(精神疾患)急性期・病院基盤モデル機関',
    title_zh: '(精神疾病)急性期·医院基础试点机构',
    hira_cd: ['SV'],
    sort: 74,
  },
  {
    tp: 'special',
    cd: 'SW',
    nm: '(정신질환)낮병동 시범기관',
    title_en: 'Mental Illness: Day Hospital Pilot',
    title_ja: '(精神疾患)デイケアモデル機関',
    title_zh: '(精神疾病)日间病房试点机构',
    hira_cd: ['SW'],
    sort: 75,
  },
  {
    tp: 'special',
    cd: 'SX',
    nm: '(정신질환)급성기·병원기반·낮병동 시범기관',
    title_en: 'Mental Illness: Acute/Hospital-based/Day Hospital Pilot',
    title_ja: '(精神疾患)急性期・病院基盤・デイケアモデル機関',
    title_zh: '(精神疾病)急性期·医院基础·日间病房试点机构',
    hira_cd: ['SX'],
    sort: 76,
  },
  {
    tp: 'special',
    cd: 'SY',
    nm: '1형 당뇨병 환자 재택의료 시범기관',
    title_en: 'Type 1 Diabetes Home Healthcare Pilot',
    title_ja: '1型糖尿病患者 在宅医療モデル機関',
    title_zh: '1型糖尿病患者居家医疗试点机构',
    hira_cd: ['SY'],
    sort: 77,
  },
  {
    tp: 'special',
    cd: 'SZ',
    nm: '(정신질환)급성기 시범기관',
    title_en: 'Mental Illness: Acute Pilot',
    title_ja: '(精神疾患)急性期モデル機関',
    title_zh: '(精神疾病)急性期试点机构',
    hira_cd: ['SZ'],
    sort: 78,
  },
  {
    tp: 'special',
    cd: 'TC',
    nm: '(회복기)재활의료기관',
    title_en: 'Convalescent Rehabilitation Institution',
    title_ja: '(回復期)リハビリ医療機関',
    title_zh: '(恢复期)康复医疗机构',
    hira_cd: ['TC'],
    sort: 79,
  },
  {
    tp: 'special',
    cd: 'TD',
    nm: '가정용 인공호흡기 환자 재택의료 시범기관',
    title_en: 'Home Ventilator Patient Home Healthcare Pilot',
    title_ja: '在宅人工呼吸器患者 在宅医療モデル機関',
    title_zh: '家用呼吸机患者居家医疗试点机构',
    hira_cd: ['TD'],
    sort: 80,
  },
  {
    tp: 'special',
    cd: 'TF',
    nm: '장애인 치과 주치의 시범기관',
    title_en: 'Disability Dental Primary Physician Pilot',
    title_ja: '障害者歯科主治医モデル機関',
    title_zh: '残疾人牙科主治医试点机构',
    hira_cd: ['TF'],
    sort: 81,
  },
  {
    tp: 'special',
    cd: 'TG',
    nm: '심장질환자 재택의료 시범기관',
    title_en: 'Cardiac Patient Home Healthcare Pilot',
    title_ja: '心臓疾患者 在宅医療モデル機関',
    title_zh: '心脏疾病患者居家医疗试点机构',
    hira_cd: ['TG'],
    sort: 82,
  },
  {
    tp: 'special',
    cd: 'TH',
    nm: '가정형 호스피스전문기관',
    title_en: 'Home Hospice Institution',
    title_ja: '在宅型ホスピス専門機関',
    title_zh: '居家型安宁疗护专门机构',
    hira_cd: ['TH'],
    sort: 83,
  },
  {
    tp: 'special',
    cd: 'TI',
    nm: '재활환자 재택의료 시범기관',
    title_en: 'Rehabilitation Patient Home Healthcare Pilot',
    title_ja: 'リハビリ患者 在宅医療モデル機関',
    title_zh: '康复患者居家医疗试点机构',
    hira_cd: ['TI'],
    sort: 84,
  },
  {
    tp: 'special',
    cd: 'Y2',
    nm: '소아진료 지역협력체계 구축 시범기관(전체)',
    title_en: 'Pediatric Care Regional Cooperation Pilot (Full)',
    title_ja: '小児診療 地域連携体制構築モデル機関(全体)',
    title_zh: '儿童诊疗地区协作体系建设试点机构(全部)',
    hira_cd: ['Y2'],
    sort: 85,
  },
  {
    tp: 'special',
    cd: 'Y3',
    nm: '소아진료 지역협력체계 구축 시범기관(중심기관)',
    title_en: 'Pediatric Care Regional Cooperation Pilot (Hub)',
    title_ja: '小児診療 地域連携体制構築モデル機関(中心機関)',
    title_zh: '儿童诊疗地区协作体系建设试点机构(中心机构)',
    hira_cd: ['Y3'],
    sort: 86,
  },
  {
    tp: 'special',
    cd: 'Y4',
    nm: '소아진료 지역협력체계 구축 시범기관(참여기관)',
    title_en: 'Pediatric Care Regional Cooperation Pilot (Participant)',
    title_ja: '小児診療 地域連携体制構築モデル機関(参加機関)',
    title_zh: '儿童诊疗地区协作体系建设试点机构(参与机构)',
    hira_cd: ['Y4'],
    sort: 87,
  },
];

export const HEALTHCARE_CODES: HealthcareCodeSeed[] = [
  ...SUBJECTS,
  ...CLASSES,
  ...EQUIPMENTS,
  ...SEVERE,
  ...SPECIALTIES,
  ...SPECIAL,
];
