-- AlterTable
ALTER TABLE `app` MODIFY `status` ENUM('PENDING', 'ACTIVE', 'DISABLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `app_api_key` MODIFY `status` ENUM('PENDING', 'ACTIVE', 'DISABLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `app_client` MODIFY `status` ENUM('PENDING', 'ACTIVE', 'DISABLED') NOT NULL DEFAULT 'PENDING';
