-- 병원평가 등급을 컬럼으로 편다. 원본 asmGrd01~24 (02·11 은 원본에 없다 — 22개).
--
-- 값은 '1'~'5' | '등급제외' | '양호' | '0'. 원본이 등급을 숫자로, 판정을 문자열로 섞어 주는데
-- JSON_UNQUOTE(JSON_EXTRACT(...)) 가 둘 다 문자열로 정규화한다. cl_cd 와 같은 방식이다.
-- 평가 대상이 아닌 항목은 원본에 키가 없어 NULL 이 된다.
--
-- VIRTUAL 이라 저장 공간을 쓰지 않는다. 필터 성능이 필요해지면 그때 개별 인덱스를 건다
-- (36,599행이라 지금은 풀스캔도 밀리초다). 22개를 미리 인덱싱하면 적재만 느려진다.
ALTER TABLE `hira_hospital_asm`
  ADD COLUMN `asm_01` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd01'))) VIRTUAL COMMENT '급성기뇌졸중',
  ADD COLUMN `asm_03` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd03'))) VIRTUAL COMMENT '혈액투석',
  ADD COLUMN `asm_04` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd04'))) VIRTUAL COMMENT '의료급여정신과',
  ADD COLUMN `asm_05` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd05'))) VIRTUAL COMMENT '수술부위 감염예방 항생제',
  ADD COLUMN `asm_06` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd06'))) VIRTUAL COMMENT '관상동맥우회술',
  ADD COLUMN `asm_07` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd07'))) VIRTUAL COMMENT '급성상기도감염 항생제 처방률',
  ADD COLUMN `asm_08` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd08'))) VIRTUAL COMMENT '주사제 처방률',
  ADD COLUMN `asm_09` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd09'))) VIRTUAL COMMENT '약품목수',
  ADD COLUMN `asm_10` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd10'))) VIRTUAL COMMENT '요양병원',
  ADD COLUMN `asm_12` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd12'))) VIRTUAL COMMENT '대장암',
  ADD COLUMN `asm_13` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd13'))) VIRTUAL COMMENT '위암',
  ADD COLUMN `asm_14` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd14'))) VIRTUAL COMMENT '유방암',
  ADD COLUMN `asm_15` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd15'))) VIRTUAL COMMENT '폐암',
  ADD COLUMN `asm_16` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd16'))) VIRTUAL COMMENT '천식',
  ADD COLUMN `asm_17` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd17'))) VIRTUAL COMMENT '만성폐쇄성폐질환',
  ADD COLUMN `asm_18` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd18'))) VIRTUAL COMMENT '폐렴',
  ADD COLUMN `asm_19` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd19'))) VIRTUAL COMMENT '중환자실',
  ADD COLUMN `asm_20` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd20'))) VIRTUAL COMMENT '신생아중환자실',
  ADD COLUMN `asm_21` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd21'))) VIRTUAL COMMENT '마취',
  ADD COLUMN `asm_22` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd22'))) VIRTUAL COMMENT '정신건강 입원영역',
  ADD COLUMN `asm_23` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd23'))) VIRTUAL COMMENT '급성하기도감염 항생제 처방률',
  ADD COLUMN `asm_24` VARCHAR(10)
    GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.asmGrd24'))) VIRTUAL COMMENT '고혈압·당뇨병';
